language: csharp
mono: none
# dotnet: 2.1.602
dotnet: 3.1
# dist: trusty
dist: xenial

branches:
  only:
  - master
  - testing

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base-dev  

install:
  - dotnet restore RDotNet.Tests.sln
  - dotnet build --configuration Debug --no-restore  RDotNet.Tests.sln

script:
  - export R_HOME=/usr/lib/R
  - ls $R_HOME
  - dotnet test RDotNet.Tests/RDotNet.Tests.csproj
  - dotnet test RDotNet.FSharp.Tests/RDotNet.FSharp.Tests.fsproj
